language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "0.12"
  - "4"
before_install: npm install -g grunt-cli
notifications:
  email:
    on_success: change
    on_failure: change
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
